name: Django-test

on: 
  push:
    branches: 
      - master

jobs:
  test_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Prepare system
        run: |
          pip install -r requirements.txt
      - name: Make migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py check
      - name: Django test
        run: python3 manage.py test
