# Generated by Django 4.1.2 on 2022-10-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='iLaksa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Краткое описание идеи', max_length=200)),
                ('descr', models.TextField(help_text='Описание идеи подробнее', max_length=1000)),
                ('date_start', models.DateField()),
                ('status_idea', models.CharField(choices=[('t', 'Реальна'), ('z', 'Забил хуй')], default='t', help_text='Что с идеей Айлаксы сейчас', max_length=1)),
                ('date_finish', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
    ]
