# Generated by Django 4.1.2 on 2022-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilaksa',
            name='descr',
            field=models.TextField(blank=True, help_text='Описание идеи подробнее', max_length=1000),
        ),
    ]
